from streamlit_webrtc import VideoProcessorBase
import threading
import cv2
import av
import os
import numpy as np
import mediapipe as mp

from mediapipe.tasks import python
from mediapipe.tasks.python import vision

from detectors.Biceps_curl import BicepsCurlDetector
from detectors.Lunges import LungesDetector
from detectors.Pushup import PushUpDetector
from detectors.Shoulder_press import ShoulderPressDetector
from detectors.Squat import SquatDetector

from services.config.workout_config import POSE_CONNECTIONS


class VideoProcessorClass(VideoProcessorBase):

    def __init__(self):

        # --------------------------------------------------
        # Thread safety
        # --------------------------------------------------

        self._lock = threading.Lock()

        # Latest metrics generated by detector
        self._latest_metrics = None

        # Default exercise
        self._exercise_type = "Squats"

        # --------------------------------------------------
        # MediaPipe model
        # --------------------------------------------------

        model_path = os.path.join(
            os.getcwd(),
            "ml_models",
            "pose_landmarker_full.task"
        )

        # Check whether model exists
        if not os.path.exists(model_path):
            raise FileNotFoundError(
                f"Pose model not found at: {model_path}"
            )

        base_options = python.BaseOptions(
            model_asset_path=model_path
        )

        options = vision.PoseLandmarkerOptions(
            base_options=base_options,
            running_mode=vision.RunningMode.VIDEO,
            min_pose_detection_confidence=0.7,
            min_pose_presence_confidence=0.7,
            min_tracking_confidence=0.7,
            output_segmentation_masks=False
        )

        self._landmarker = (
            vision.PoseLandmarker.create_from_options(
                options
            )
        )

        # --------------------------------------------------
        # Exercise detectors
        # --------------------------------------------------

        self._detectors = {
            "Squats": SquatDetector(),
            "Biceps Curls (Dumbbell)": BicepsCurlDetector(),
            "Push-ups": PushUpDetector(),
            "Lunges": LungesDetector(),
            "Shoulder Press": ShoulderPressDetector()
        }

        # MediaPipe VIDEO mode timestamp
        self._frame_timestamps_ms = 0

    # ======================================================
    # METRICS
    # ======================================================

    def set_latest_metrics(self, metrics):

        with self._lock:

            if metrics is None:
                self._latest_metrics = None
            else:
                self._latest_metrics = metrics.copy()

    def get_latest_metrics(self):

        with self._lock:

            if self._latest_metrics is None:
                return None

            return self._latest_metrics.copy()

    # ======================================================
    # EXERCISE
    # ======================================================

    def set_exercise(self, exercise_type):

        with self._lock:
            self._exercise_type = exercise_type

    def get_exercise(self):

        with self._lock:
            return self._exercise_type

    # ======================================================
    # DRAW SKELETON
    # ======================================================

    def _draw_skeleton(self, img, landmarks):

        h, w = img.shape[:2]

        # --------------------------------------------------
        # Draw connections between landmarks
        # --------------------------------------------------

        for start_idx, end_idx in POSE_CONNECTIONS:

            p1 = landmarks[start_idx]
            p2 = landmarks[end_idx]

            if (
                p1.visibility > 0.7
                and p2.visibility > 0.7
            ):

                x1 = int(p1.x * w)
                y1 = int(p1.y * h)

                x2 = int(p2.x * w)
                y2 = int(p2.y * h)

                cv2.line(
                    img,
                    (x1, y1),
                    (x2, y2),
                    (0, 255, 0),
                    3
                )

        # --------------------------------------------------
        # Draw individual landmarks
        # --------------------------------------------------

        for landmark in landmarks:

            if landmark.visibility > 0.7:

                x = int(landmark.x * w)
                y = int(landmark.y * h)

                cv2.circle(
                    img,
                    (x, y),
                    6,
                    (255, 0, 0),
                    -1
                )

        return img

    # ======================================================
    # NO POSE WARNING
    # ======================================================

    def _draw_no_pose_warnings(self, img):

        cv2.putText(
            img,
            "No Pose Detected",
            (30, 50),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0, 255, 0),
            2,
            cv2.LINE_AA
        )

        cv2.putText(
            img,
            "Please Face the Camera",
            (30, 100),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0, 255, 0),
            2,
            cv2.LINE_AA
        )

    # ======================================================
    # EXERCISE OVERLAYS
    # ======================================================

    def _draw_overlays(self, img, metrics, exercise_type):

        if metrics is None:
            return

        if exercise_type == "Squats":

            self._draw_squats_overlays(
                img,
                metrics
            )

        elif exercise_type == "Push-ups":

            self._draw_pushup_overlays(
                img,
                metrics
            )

        elif exercise_type == "Biceps Curls (Dumbbell)":

            self._draw_curl_overlays(
                img,
                metrics
            )

        elif exercise_type == "Shoulder Press":

            self._draw_press_overlays(
                img,
                metrics
            )

        elif exercise_type == "Lunges":

            self._draw_lunge_overlays(
                img,
                metrics
            )

    # ======================================================
    # SQUAT OVERLAY
    # ======================================================

    def _draw_squats_overlays(self, img, metrics):

        h, _ = img.shape[:2]

        depth_status = metrics.get(
            "depth_status",
            "Unknown"
        )

        cv2.putText(
            img,
            f"DEPTH: {depth_status}",
            (20, h - 20),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0, 255, 0),
            2,
            cv2.LINE_AA
        )

    # ======================================================
    # PUSH-UP OVERLAY
    # ======================================================

    def _draw_pushup_overlays(self, img, metrics):

        h, _ = img.shape[:2]

        body_alignment = metrics.get(
            "body_alignment",
            "Unknown"
        )

        hip_status = metrics.get(
            "hip_status",
            "Unknown"
        )

        cv2.putText(
            img,
            f"BODY: {body_alignment} | HIP: {hip_status}",
            (20, h - 20),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 255, 0),
            2,
            cv2.LINE_AA
        )

    # ======================================================
    # BICEPS CURL OVERLAY
    # ======================================================

    def _draw_curl_overlays(self, img, metrics):

        h, _ = img.shape[:2]

        swing_status = metrics.get(
            "swing_status",
            "Unknown"
        )

        cv2.putText(
            img,
            f"SWING: {swing_status}",
            (20, h - 20),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0, 255, 0),
            2,
            cv2.LINE_AA
        )

    # ======================================================
    # SHOULDER PRESS OVERLAY
    # ======================================================

    def _draw_press_overlays(self, img, metrics):

        h, _ = img.shape[:2]

        extension_status = metrics.get(
            "extension_status",
            "Unknown"
        )

        back_arch_status = metrics.get(
            "back_arch_status",
            "Unknown"
        )

        cv2.putText(
            img,
            f"EXT: {extension_status} | BACK: {back_arch_status}",
            (20, h - 20),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 255, 0),
            2,
            cv2.LINE_AA
        )

    # ======================================================
    # LUNGE OVERLAY
    # ======================================================

    def _draw_lunge_overlays(self, img, metrics):

        h, _ = img.shape[:2]

        balance_status = metrics.get(
            "balance_status",
            "Unknown"
        )

        cv2.putText(
            img,
            f"BALANCE: {balance_status}",
            (20, h - 20),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0, 255, 0),
            2,
            cv2.LINE_AA
        )

    # ======================================================
    # PROCESS VIDEO FRAME
    # ======================================================

    def recv(self, frame):

        # --------------------------------------------------
        # WebRTC frame -> OpenCV BGR image
        # --------------------------------------------------

        image = frame.to_ndarray(
            format="bgr24"
        )

        # Mirror the webcam
        image = cv2.flip(
            image,
            1
        )

        # --------------------------------------------------
        # BGR -> RGB
        # MediaPipe expects RGB/SRGB
        # --------------------------------------------------

        rgb_image = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2RGB
        )

        # --------------------------------------------------
        # Create MediaPipe Image
        # --------------------------------------------------

        mp_image = mp.Image(
            image_format=mp.ImageFormat.SRGB,
            data=rgb_image
        )

        # --------------------------------------------------
        # Increase timestamp
        # --------------------------------------------------

        self._frame_timestamps_ms += 30

        # --------------------------------------------------
        # Run pose detection
        # --------------------------------------------------

        result = self._landmarker.detect_for_video(
            mp_image,
            self._frame_timestamps_ms
        )

        # --------------------------------------------------
        # Pose detected
        # --------------------------------------------------

        if result.pose_landmarks:

            # First detected person
            landmarks = result.pose_landmarks[0]

            # Draw skeleton
            self._draw_skeleton(
                image,
                landmarks
            )

            # Get selected exercise
            exercise_type = self.get_exercise()

            # Get corresponding detector
            detector = self._detectors.get(
                exercise_type
            )

            if detector:

                # Process landmarks
                metrics = detector.process(
                    landmarks
                )

                # Draw exercise information
                self._draw_overlays(
                    image,
                    metrics,
                    exercise_type
                )

                # Store latest metrics
                self.set_latest_metrics(
                    metrics
                )

        # --------------------------------------------------
        # No pose detected
        # --------------------------------------------------

        else:

            self._draw_no_pose_warnings(
                image
            )

            self.set_latest_metrics(
                None
            )

        # --------------------------------------------------
        # Return processed frame
        # --------------------------------------------------

        return av.VideoFrame.from_ndarray(
            image,
            format="bgr24"
        )